"""🗒️ Note data models with enhanced metadata and capabilities.

Modern note models supporting rich metadata, embeddings, and agentic features.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, computed_field, field_validator, model_validator


class NoteMetadata(BaseModel):
    """Rich metadata for notes with semantic information."""
    
    # Organizational metadata
    tags: List[str] = Field(
        default_factory=list,
        description="Tags for categorization",
        max_length=20
    )
    category: Optional[str] = Field(
        default=None,
        description="Primary category",
        max_length=50
    )
    priority: int = Field(
        default=0,
        ge=-5,
        le=5,
        description="Priority from -5 (low) to 5 (high)"
    )
    
    # Source information
    source_url: Optional[str] = Field(
        default=None,
        description="Source URL if note is from web content"
    )
    source_type: Optional[str] = Field(
        default=None,
        description="Source type (web, book, meeting, etc.)"
    )
    author: Optional[str] = Field(
        default=None,
        description="Original author if different from creator"
    )
    
    # Semantic metadata (auto-generated by agents)
    topics: List[str] = Field(
        default_factory=list,
        description="Auto-extracted topics",
        max_length=15
    )
    entities: List[str] = Field(
        default_factory=list,
        description="Named entities (people, places, organizations)",
        max_length=25
    )
    keywords: List[str] = Field(
        default_factory=list,
        description="Auto-extracted keywords",
        max_length=30
    )
    sentiment_score: Optional[float] = Field(
        default=None,
        ge=-1.0,
        le=1.0,
        description="Sentiment score from -1 (negative) to 1 (positive)"
    )
    complexity_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Content complexity score from 0 (simple) to 1 (complex)"
    )
    
    # Relationships
    related_notes: List[str] = Field(
        default_factory=list,
        description="IDs of related notes",
        max_length=50
    )
    parent_note_id: Optional[str] = Field(
        default=None,
        description="Parent note ID if this is a sub-note"
    )
    
    # Custom fields for extensibility
    custom_fields: Dict[str, Any] = Field(
        default_factory=dict,
        description="Custom metadata fields"
    )
    
    @field_validator("tags", "topics", "entities", "keywords")
    @classmethod
    def clean_string_lists(cls, v: List[str]) -> List[str]:
        """Clean and deduplicate string lists."""
        if not v:
            return []
        
        # Clean, filter, and deduplicate
        cleaned = []
        seen = set()
        for item in v:
            clean_item = item.strip().lower()
            if clean_item and clean_item not in seen and len(clean_item) <= 100:
                cleaned.append(clean_item)
                seen.add(clean_item)
        
        return cleaned
    
    @field_validator("category")
    @classmethod
    def clean_category(cls, v: Optional[str]) -> Optional[str]:
        """Clean category name."""
        if not v:
            return None
        return v.strip().lower()


class NoteCreate(BaseModel):
    """Model for creating a new note."""
    
    title: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Note title"
    )
    content: str = Field(
        ...,
        min_length=1,
        max_length=100_000,
        description="Note content in markdown format"
    )
    metadata: NoteMetadata = Field(
        default_factory=NoteMetadata,
        description="Note metadata"
    )
    
    @field_validator("title", "content")
    @classmethod
    def clean_text(cls, v: str) -> str:
        """Clean and validate text content."""
        return v.strip()
    
    @computed_field
    @property
    def word_count(self) -> int:
        """Calculate word count of content."""
        return len(self.content.split())
    
    @computed_field
    @property
    def char_count(self) -> int:
        """Calculate character count of content."""
        return len(self.content)


class NoteUpdate(BaseModel):
    """Model for updating an existing note."""
    
    title: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=200,
        description="Updated title"
    )
    content: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=100_000,
        description="Updated content"
    )
    metadata: Optional[NoteMetadata] = Field(
        default=None,
        description="Updated metadata"
    )
    
    @field_validator("title", "content")
    @classmethod
    def clean_text(cls, v: Optional[str]) -> Optional[str]:
        """Clean text content if provided."""
        return v.strip() if v is not None else None
    
    @model_validator(mode="after")
    def validate_at_least_one_field(self) -> NoteUpdate:
        """Ensure at least one field is provided for update."""
        if not any([self.title, self.content, self.metadata]):
            raise ValueError("At least one field must be provided for update")
        return self


class Note(BaseModel):
    """Complete note model with all fields and computed properties."""
    
    # Core fields
    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique note identifier"
    )
    title: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Note title"
    )
    content: str = Field(
        ...,
        min_length=1,
        max_length=100_000,
        description="Note content in markdown format"
    )
    
    # Metadata
    metadata: NoteMetadata = Field(
        default_factory=NoteMetadata,
        description="Rich note metadata"
    )
    
    # Timestamps
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Creation timestamp"
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Last update timestamp"
    )
    
    # System fields
    version: int = Field(
        default=1,
        ge=1,
        description="Note version for optimistic locking"
    )
    is_archived: bool = Field(
        default=False,
        description="Whether the note is archived"
    )
    is_favorite: bool = Field(
        default=False,
        description="Whether the note is marked as favorite"
    )
    
    # AI-generated fields (populated by agents)
    embedding_vector: Optional[List[float]] = Field(
        default=None,
        description="Semantic embedding vector"
    )
    summary: Optional[str] = Field(
        default=None,
        max_length=500,
        description="AI-generated summary"
    )
    
    # Analytics
    view_count: int = Field(
        default=0,
        ge=0,
        description="Number of times note was viewed"
    )
    last_accessed: Optional[datetime] = Field(
        default=None,
        description="Last time note was accessed"
    )
    
    class Config:
        """Pydantic configuration."""
        json_encoders = {
            datetime: lambda v: v.isoformat() if v else None
        }
        populate_by_name = True
        validate_assignment = True
    
    @computed_field
    @property
    def word_count(self) -> int:
        """Calculate word count of content."""
        return len(self.content.split())
    
    @computed_field
    @property
    def char_count(self) -> int:
        """Calculate character count of content."""
        return len(self.content)
    
    @computed_field
    @property
    def reading_time_minutes(self) -> int:
        """Estimate reading time in minutes (average 200 words/min)."""
        return max(1, self.word_count // 200)
    
    @computed_field
    @property
    def has_embedding(self) -> bool:
        """Check if note has an embedding vector."""
        return bool(self.embedding_vector)
    
    @computed_field
    @property
    def tag_string(self) -> str:
        """Get tags as a comma-separated string."""
        return ", ".join(self.metadata.tags)
    
    @computed_field
    @property
    def age_days(self) -> int:
        """Calculate age of note in days."""
        return (datetime.now(timezone.utc) - self.created_at).days
    
    def has_tag(self, tag: str) -> bool:
        """Check if note has a specific tag."""
        return tag.lower() in [t.lower() for t in self.metadata.tags]
    
    def has_topic(self, topic: str) -> bool:
        """Check if note contains a specific topic."""
        return topic.lower() in [t.lower() for t in self.metadata.topics]
    
    def has_entity(self, entity: str) -> bool:
        """Check if note contains a specific entity."""
        return entity.lower() in [e.lower() for e in self.metadata.entities]
    
    def is_related_to(self, note_id: str) -> bool:
        """Check if this note is related to another note."""
        return note_id in self.metadata.related_notes
    
    def add_tag(self, tag: str) -> None:
        """Add a tag to the note."""
        clean_tag = tag.strip().lower()
        if clean_tag and clean_tag not in [t.lower() for t in self.metadata.tags]:
            self.metadata.tags.append(clean_tag)
            self.updated_at = datetime.now(timezone.utc)
            self.version += 1
    
    def remove_tag(self, tag: str) -> None:
        """Remove a tag from the note."""
        clean_tag = tag.strip().lower()
        self.metadata.tags = [
            t for t in self.metadata.tags if t.lower() != clean_tag
        ]
        self.updated_at = datetime.now(timezone.utc)
        self.version += 1
    
    def mark_accessed(self) -> None:
        """Mark note as accessed and increment view count."""
        self.last_accessed = datetime.now(timezone.utc)
        self.view_count += 1
    
    def archive(self) -> None:
        """Archive the note."""
        self.is_archived = True
        self.updated_at = datetime.now(timezone.utc)
        self.version += 1
    
    def unarchive(self) -> None:
        """Unarchive the note."""
        self.is_archived = False
        self.updated_at = datetime.now(timezone.utc)
        self.version += 1
    
    def toggle_favorite(self) -> None:
        """Toggle favorite status."""
        self.is_favorite = not self.is_favorite
        self.updated_at = datetime.now(timezone.utc)
        self.version += 1
    
    def update_content(self, title: Optional[str] = None, content: Optional[str] = None) -> None:
        """Update note content and timestamps."""
        if title is not None:
            self.title = title.strip()
        if content is not None:
            self.content = content.strip()
        
        if title is not None or content is not None:
            self.updated_at = datetime.now(timezone.utc)
            self.version += 1
    
    def model_dump_public(self) -> Dict[str, Any]:
        """Export note data without sensitive internal fields."""
        data = self.model_dump()
        
        # Remove internal/sensitive fields
        data.pop("embedding_vector", None)
        data.pop("version", None)
        
        return data